const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{MarcadorX: 0},
	{MarcadorY: 0},
	{PiezaID: 0},
	{MarcadorID: 0},
	{Pieza1: 0},
	{Pieza2: 0},
	{Pieza3: 0},
	{Pieza4: 0},
	{Pieza5: 0},
	{Pieza6: 0},
	{Pieza7: 0},
	{Pieza8: 0},
	{Pieza9: 0},
	{Fondo: 0},
	{Marcador: 0},
	{Sprite: 0},
	{pag3: 0},
	{Sprite2: 0},
	{Text2: 0},
	{Text3: 0},
	{Nuez: 0},
	{Bosque: 0},
	{Fade: 0},
	{EncuentraLasBellotas: 0},
	{ContBellotas: 0},
	{Touch: 0},
	{Mouse: 0},
	{Bellotas: 0},
	{Plumas: 0},
	{Pagina: 0},
	{PiezasCorrectas: 0},
	{PlumasCaen: 0},
	{Sprite3: 0},
	{BellotasCont: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{Sprite4: 0},
	{BosqueAve: 0},
	{DragDrop: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{FondoAnimado: 0},
	{Boton: 0},
	{EncuentraLasBellotas2: 0},
	{PlumasCOnt: 0},
	{ContPlumas: 0},
	{Menu: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{BotonCuento1: 0},
	{Sprite9: 0},
	{BotonCuento2: 0},
	{Piezas: 0}
];

self.InstanceType = {
	Pieza1: class extends self.ISpriteInstance {},
	Pieza2: class extends self.ISpriteInstance {},
	Pieza3: class extends self.ISpriteInstance {},
	Pieza4: class extends self.ISpriteInstance {},
	Pieza5: class extends self.ISpriteInstance {},
	Pieza6: class extends self.ISpriteInstance {},
	Pieza7: class extends self.ISpriteInstance {},
	Pieza8: class extends self.ISpriteInstance {},
	Pieza9: class extends self.ISpriteInstance {},
	Fondo: class extends self.ISpriteInstance {},
	Marcador: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	pag3: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Nuez: class extends self.ISpriteInstance {},
	Bosque: class extends self.ISpriteInstance {},
	EncuentraLasBellotas: class extends self.ITextInstance {},
	ContBellotas: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BellotasCont: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BosqueAve: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	FondoAnimado: class extends self.ISpriteInstance {},
	Boton: class extends self.ISpriteInstance {},
	EncuentraLasBellotas2: class extends self.ITextInstance {},
	PlumasCOnt: class extends self.ITextInstance {},
	ContPlumas: class extends self.ITextInstance {},
	Menu: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	BotonCuento1: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	BotonCuento2: class extends self.ISpriteInstance {},
	Piezas: class extends self.ISpriteInstance {}
}