const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.BinaryData,
		C3.Plugins.Json,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Behaviors.EightDir,
		C3.Behaviors.Flash,
		C3.Behaviors.bound,
		C3.Plugins.Audio,
		C3.Behaviors.Turret,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Turret.Cnds.HasTarget,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{EscenarioAgave: 0},
	{HUDAxi: 0},
	{Ilustración_sin_título: 0},
	{Fade: 0},
	{Ilustración_sin_título2: 0},
	{IMG_: 0},
	{MODODEJUEGO: 0},
	{SELECCIONAPERSONAJE: 0},
	{SELECCIONDENIVEL: 0},
	{Agave: 0},
	{Cascadas: 0},
	{Contrarreloj: 0},
	{Empezar: 0},
	{PlayerSelect: 0},
	{Record: 0},
	{Volcan: 0},
	{Restart: 0},
	{SelectAxi: 0},
	{SelectBalanox: 0},
	{SelectTlalic: 0},
	{AJAX: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{Keyboard: 0},
	{BinaryData: 0},
	{JSON_Leaderboard: 0},
	{Touch: 0},
	{AreaDeGolpeo: 0},
	{Dir: 0},
	{ChangeView: 0},
	{PlayerSpawn: 0},
	{PuntoGolpe: 0},
	{SpawnPoint: 0},
	{Sprite: 0},
	{Solid: 0},
	{Delimitadores: 0},
	{ScrollTo: 0},
	{Camara: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rayocondensado: 0},
	{SpawnPointTilapiaRoja: 0},
	{Barra_base: 0},
	{Barra_Hp: 0},
	{Barra_Pwp: 0},
	{BotonAgave: 0},
	{BotonCascada: 0},
	{BotonVolcan: 0},
	{Combo_Bar: 0},
	{Combo_BarFondo: 0},
	{ComboText: 0},
	{ScoreText: 0},
	{MainMenu: 0},
	{NombreJugador: 0},
	{NombreDeJugador: 0},
	{Text: 0},
	{TimerText: 0},
	{HP: 0},
	{MaxHP: 0},
	{AttackBuffer: 0},
	{ComboState: 0},
	{ComboResetTimer: 0},
	{Health: 0},
	{SpecialCooldown: 0},
	{Axi: 0},
	{Active: 0},
	{MoveDirection: 0},
	{PatrolTimer: 0},
	{StunTimer: 0},
	{ThreatValue: 0},
	{IsActive: 0},
	{state: 0},
	{"8Direction": 0},
	{Flash: 0},
	{BoundToLayout: 0},
	{TilapiaDeAsalto: 0},
	{UnstoppableTimer: 0},
	{Balanox: 0},
	{AttackRange: 0},
	{AIState: 0},
	{AttackCoolDown: 0},
	{DetectionRange: 0},
	{TilapiaArtillera: 0},
	{Tlalic: 0},
	{ezgifframe: 0},
	{ezgifframe2: 0},
	{Audio: 0},
	{Turret: 0},
	{Sine: 0},
	{TilapiaVoladora: 0},
	{Sprite2: 0},
	{BotonCuadrado: 0},
	{Botón: 0},
	{botonCirculo: 0},
	{Text2: 0},
	{barraPersonaje: 0},
	{barraPersonaje2: 0},
	{profile: 0},
	{corazonIcon: 0},
	{poderIcon: 0},
	{GAMESPIRATIONLOGOSRGB: 0},
	{backGamespir: 0},
	{"8Direction2": 0},
	{Player_Family: 0},
	{Enemy_Family: 0},
	{LL_APIKey: 0},
	{LL_LeaderboardID: 0},
	{LL_SessionToken: 0},
	{LL_PlayerID: 0},
	{Score: 0},
	{ComboMultiplier: 0},
	{ComboTimer: 0},
	{SelectCharacter: 0},
	{SelectMap: 0},
	{MaxComboTime: 0},
	{GameMode: 0},
	{Timer: 0},
	{CurrentWave: 0},
	{WaveBudget: 0},
	{WaveInProgress: 0},
	{EnemiesAlive: 0},
	{Activos: 0},
	{WaveNumber: 0},
	{Name: 0},
	{MenuIndex: 0}
];

self.InstanceType = {
	EscenarioAgave: class extends self.ISpriteInstance {},
	HUDAxi: class extends self.ISpriteInstance {},
	Ilustración_sin_título: class extends self.ISpriteInstance {},
	Ilustración_sin_título2: class extends self.ISpriteInstance {},
	IMG_: class extends self.ISpriteInstance {},
	MODODEJUEGO: class extends self.ISpriteInstance {},
	SELECCIONAPERSONAJE: class extends self.ISpriteInstance {},
	SELECCIONDENIVEL: class extends self.ISpriteInstance {},
	Agave: class extends self.IButtonInstance {},
	Cascadas: class extends self.IButtonInstance {},
	Contrarreloj: class extends self.IButtonInstance {},
	Empezar: class extends self.IButtonInstance {},
	PlayerSelect: class extends self.IButtonInstance {},
	Record: class extends self.IButtonInstance {},
	Volcan: class extends self.IButtonInstance {},
	Restart: class extends self.IButtonInstance {},
	SelectAxi: class extends self.IButtonInstance {},
	SelectBalanox: class extends self.IButtonInstance {},
	SelectTlalic: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	JSON_Leaderboard: class extends self.IJSONInstance {},
	Touch: class extends self.IInstance {},
	AreaDeGolpeo: class extends self.ISpriteInstance {},
	ChangeView: class extends self.ISpriteInstance {},
	PlayerSpawn: class extends self.ISpriteInstance {},
	PuntoGolpe: class extends self.ISpriteInstance {},
	SpawnPoint: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Delimitadores: class extends self.ISpriteInstance {},
	Camara: class extends self.ISpriteInstance {},
	Rayocondensado: class extends self.ISpriteInstance {},
	SpawnPointTilapiaRoja: class extends self.ISpriteInstance {},
	Barra_base: class extends self.ISpriteInstance {},
	Barra_Hp: class extends self.ISpriteInstance {},
	Barra_Pwp: class extends self.ISpriteInstance {},
	BotonAgave: class extends self.ISpriteInstance {},
	BotonCascada: class extends self.ISpriteInstance {},
	BotonVolcan: class extends self.ISpriteInstance {},
	Combo_Bar: class extends self.ISpriteInstance {},
	Combo_BarFondo: class extends self.ISpriteInstance {},
	ComboText: class extends self.ITextInstance {},
	ScoreText: class extends self.ITextInstance {},
	MainMenu: class extends self.ITextInstance {},
	NombreDeJugador: class extends self.ITextInputInstance {},
	Text: class extends self.ITextInstance {},
	TimerText: class extends self.ITextInstance {},
	Axi: class extends self.ISpriteInstance {},
	TilapiaDeAsalto: class extends self.ISpriteInstance {},
	Balanox: class extends self.ISpriteInstance {},
	TilapiaArtillera: class extends self.ISpriteInstance {},
	Tlalic: class extends self.ISpriteInstance {},
	ezgifframe: class extends self.ISpriteInstance {},
	ezgifframe2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	TilapiaVoladora: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	BotonCuadrado: class extends self.ISpriteInstance {},
	Botón: class extends self.ISpriteInstance {},
	botonCirculo: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	barraPersonaje: class extends self.ISpriteInstance {},
	barraPersonaje2: class extends self.ISpriteInstance {},
	profile: class extends self.ISpriteInstance {},
	corazonIcon: class extends self.ISpriteInstance {},
	poderIcon: class extends self.ISpriteInstance {},
	GAMESPIRATIONLOGOSRGB: class extends self.ISpriteInstance {},
	backGamespir: class extends self.ISpriteInstance {},
	Player_Family: class extends self.ISpriteInstance {},
	Enemy_Family: class extends self.ISpriteInstance {}
}