const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.NinePatch,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{BushDouble: 0},
	{BushSingle: 0},
	{BushTriple: 0},
	{CloudDouble: 0},
	{CloudSingle: 0},
	{CloudTriple: 0},
	{HillLarge: 0},
	{HillSmall: 0},
	{Solid: 0},
	{Brick: 0},
	{Sólido: 0},
	{MarioFloor: 0},
	{QuestionBlock: 0},
	{TiledBlock: 0},
	{Direction: 0},
	{Platform: 0},
	{Goomba: 0},
	{triggerDirection: 0},
	{Mario: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{MarioController: 0},
	{Keyboard: 0},
	{Pipe: 0},
	{Pole: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{direction: 0},
	{GreenKoopaTroopa: 0},
	{TriggerCaida: 0},
	{Audio: 0},
	{Coin: 0},
	{Coins: 0},
	{Coins2: 0},
	{Bowser: 0},
	{Sine: 0},
	{MovingPlatform: 0},
	{Bullet: 0},
	{Fireball: 0},
	{lava: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{coins: 0}
];

self.InstanceType = {
	BushDouble: class extends self.ISpriteInstance {},
	BushSingle: class extends self.ISpriteInstance {},
	BushTriple: class extends self.ISpriteInstance {},
	CloudDouble: class extends self.ISpriteInstance {},
	CloudSingle: class extends self.ISpriteInstance {},
	CloudTriple: class extends self.ISpriteInstance {},
	HillLarge: class extends self.ISpriteInstance {},
	HillSmall: class extends self.ISpriteInstance {},
	Brick: class extends self.ISpriteInstance {},
	MarioFloor: class extends self.ITiledBackgroundInstance {},
	QuestionBlock: class extends self.ISpriteInstance {},
	TiledBlock: class extends self.ITiledBackgroundInstance {},
	Goomba: class extends self.ISpriteInstance {},
	triggerDirection: class extends self.ISpriteInstance {},
	Mario: class extends self.ISpriteInstance {},
	MarioController: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Pipe: class extends self.I9PatchInstance {},
	Pole: class extends self.I9PatchInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	GreenKoopaTroopa: class extends self.ISpriteInstance {},
	TriggerCaida: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Coin: class extends self.ISpriteInstance {},
	Coins: class extends self.ITextInstance {},
	Coins2: class extends self.ITextInstance {},
	Bowser: class extends self.ISpriteInstance {},
	MovingPlatform: class extends self.ISpriteInstance {},
	Fireball: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {}
}