const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Behaviors.ppstudiosmartui_button_beh,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Plugins.ppstudio_smartui_plugin,
		C3.Plugins.Touch,
		C3.Behaviors.ppstudio_beh_fsm,
		C3.Behaviors.Turret,
		C3.Plugins.Audio,
		C3.Plugins.ppstudio_fsm,
		C3.Behaviors.ppstudio_container_beh,
		C3.Behaviors.ppstudio_dialog_beh,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.ppstudiosmartui_button_beh.Cnds.OnReleased,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Behaviors.ppstudiosmartui_button_beh.Acts.SetNormalAnimation,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.ppstudio_beh_fsm.Cnds.CurrentState,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.ppstudio_beh_fsm.Acts.ChangeState,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.ppstudiosmartui_button_beh.Cnds.IsPressed,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.ppstudiosmartui_button_beh.Cnds.OnClick,
		C3.Plugins.Sprite.Exps.Tags,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Candy: 0},
	{Physics: 0},
	{Candy_Controller: 0},
	{Hook: 0},
	{Processed: 0},
	{Punto_de_anclaje: 0},
	{UID_Anclaje: 0},
	{Fade: 0},
	{Rope_Controller: 0},
	{Rope_Controller2: 0},
	{Rope_Controller3: 0},
	{Rope_Controller4: 0},
	{Rope_Controller5: 0},
	{Punto_de_anclaje2: 0},
	{Punto_de_anclaje3: 0},
	{Slice: 0},
	{SliceInitialX: 0},
	{SliceInitialY: 0},
	{Slice_Controller: 0},
	{TitlerBackground: 0},
	{Background: 0},
	{Background_Box: 0},
	{Background_support: 0},
	{Button: 0},
	{ButtonMusic: 0},
	{Engine_Button: 0},
	{JugarButton: 0},
	{ButtonSFX: 0},
	{ButtonExit: 0},
	{Music: 0},
	{SFX: 0},
	{Star1: 0},
	{Star2: 0},
	{Star3: 0},
	{Tween: 0},
	{Stars: 0},
	{ReloadButton: 0},
	{ButtonSmall: 0},
	{ReloadWhite: 0},
	{Der: 0},
	{Izq: 0},
	{ButtonGreen: 0},
	{Next: 0},
	{"9patch": 0},
	{Finger: 0},
	{Arrow: 0},
	{Text1LVL1: 0},
	{Text1LVL2: 0},
	{Text1LVL3: 0},
	{ButtonPlay: 0},
	{SmartUI: 0},
	{Touch: 0},
	{SFX_eating: 0},
	{FSM: 0},
	{Char: 0},
	{Star: 0},
	{Turret: 0},
	{Char_Controller: 0},
	{Audio: 0},
	{Pointer: 0},
	{Rope_height: 0},
	{TotalDistance: 0},
	{RopeCount: 0},
	{lastLinkUID: 0},
	{candy_angle: 0},
	{dx: 0},
	{dy: 0},
	{StepX: 0},
	{StepY: 0},
	{DistanceNearest: 0},
	{Layout: 0},
	{GameController: 0},
	{CandyCrash: 0},
	{Follow: 0},
	{BurbujaController: 0},
	{Burbuja: 0},
	{Container: 0},
	{MenuContainer: 0},
	{BotonMenu: 0},
	{Text: 0},
	{Cinta: 0},
	{Cut: 0},
	{Splash: 0},
	{Pausado: 0},
	{PauseButon: 0},
	{Dialog: 0},
	{DestroyOutsideLayout: 0},
	{PauseDialog: 0},
	{Physics2: 0},
	{ChainLink: 0},
	{PointAnclaje: 0},
	{de: 0},
	{PuntoAnclajeUID: 0},
	{DestroyUID: 0},
	{MusicToggle: 0},
	{SFXToggle: 0}
];

self.InstanceType = {
	Candy: class extends self.ISpriteInstance {},
	Candy_Controller: class extends self.ISpriteInstance {},
	Hook: class extends self.ISpriteInstance {},
	Punto_de_anclaje: class extends self.ISpriteInstance {},
	Rope_Controller: class extends self.ISpriteInstance {},
	Rope_Controller2: class extends self.ISpriteInstance {},
	Rope_Controller3: class extends self.ISpriteInstance {},
	Rope_Controller4: class extends self.ISpriteInstance {},
	Rope_Controller5: class extends self.ISpriteInstance {},
	Punto_de_anclaje2: class extends self.ISpriteInstance {},
	Punto_de_anclaje3: class extends self.ISpriteInstance {},
	Slice: class extends self.ISpriteInstance {},
	Slice_Controller: class extends self.ISpriteInstance {},
	TitlerBackground: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Background_Box: class extends self.ISpriteInstance {},
	Background_support: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	ButtonMusic: class extends self.ISpriteInstance {},
	Engine_Button: class extends self.ISpriteInstance {},
	JugarButton: class extends self.ITextInstance {},
	ButtonSFX: class extends self.ISpriteInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	SFX: class extends self.ISpriteInstance {},
	Star1: class extends self.ISpriteInstance {},
	Star2: class extends self.ISpriteInstance {},
	Star3: class extends self.ISpriteInstance {},
	Stars: class extends self.ISpriteInstance {},
	ReloadButton: class extends self.ISpriteInstance {},
	ButtonSmall: class extends self.ISpriteInstance {},
	ReloadWhite: class extends self.ISpriteInstance {},
	Der: class extends self.ISpriteInstance {},
	Izq: class extends self.ISpriteInstance {},
	ButtonGreen: class extends self.ISpriteInstance {},
	Next: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	Finger: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Text1LVL1: class extends self.ITextInstance {},
	Text1LVL2: class extends self.ITextInstance {},
	Text1LVL3: class extends self.ITextInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	SmartUI: class extends C3.Plugins.ppstudio_smartui_plugin.Instance {},
	Touch: class extends self.IInstance {},
	Char: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Char_Controller: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	GameController: class extends self.ISpriteInstance {},
	CandyCrash: class extends self.ISpriteInstance {},
	FSM: class extends C3.Plugins.ppstudio_fsm.Instance {},
	BurbujaController: class extends self.ISpriteInstance {},
	Burbuja: class extends self.ISpriteInstance {},
	MenuContainer: class extends self.ISpriteInstance {},
	BotonMenu: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Cinta: class extends self.ISpriteInstance {},
	Cut: class extends self.ISpriteInstance {},
	Splash: class extends self.ISpriteInstance {},
	PauseButon: class extends self.ISpriteInstance {},
	PauseDialog: class extends self.ISpriteInstance {},
	ChainLink: class extends self.ISpriteInstance {},
	PointAnclaje: class extends self.ISpriteInstance {}
}